# Copyright (c) 2026 By David "Hankinsohl" Hankins.
# This software is licensed under the terms of the MIT License.
# Created by Hankinsohl on 2/18/2026.

# Set game_variant to "Poe1" or "Poe2".  Used for test builds only.
game_variant = "Poe1"

# Set repository to "Local" or "Remote"
repository = "Local"

# Path to repository root directory.  Ignored if repository is "Remote"
root_path = "e:/poe/repository"
